name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
      name: Build and Test 👷🏻
      timeout-minutes: 60
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v3
          with:
            version: 8
          
        - uses: actions/setup-node@v4
          with:
            check-latest: true
            node-version-file: '.nvmrc'
            cache: 'pnpm'
 
        - name: Install dependencies 🧳
          env:
            PSQL_DATABASE_URL: ${{ secrets.PSQL_DATABASE_URL }}
          run: pnpm install
          
        - name: Check Lint 💅🏻
          run: pnpm lint && pnpm typecheck && pnpm format:check

        - name: Run Build 🔨
          run: pnpm build
 